export const aboutObject = {
  src: '/images/LogoBelle.png',
  alt: 'Lighthouse Design Studio',
  imgStart: false,
  dataAosTxt: 'fade-right',
  dataAosImg: 'fade-left',
  dataAosDuration: '1000',
  dataAosEasing: 'ease-in-out',
  dataAosDelayTxt: '100',
  dataAosDelayImg: '400',
};

export const colabsObject = [
  {
    _id: 1,
    logo: '/images/Logo.png',
    alt: 'Enter colabs name',
    dataAosCard: 'zoom-in-down',
    textColor: true,
    duration: '1000',
    link: 'https://www.facebook.com',
  },
  {
    _id: 2,
    logo: '/images/Logo.png',
    alt: 'Enter colabs name',
    dataAosCard: 'zoom-in-down',
    textColor: false,
    duration: '1400',
    link: 'https://www.facebook.com',
  },
  {
    _id: 3,
    logo: '/images/Logo.png',
    alt: 'Enter colabs name',
    dataAosCard: 'zoom-in-down',
    textColor: true,
    duration: '1600',
    link: 'https://www.facebook.com',
  },
  {
    _id: 4,
    logo: '/images/Logo.png',
    alt: 'Enter colabs name',
    dataAosCard: 'zoom-in-down',
    textColor: false,
    duration: '1800',
    link: 'https://www.facebook.com',
  },
  {
    _id: 5,
    logo: '/images/Logo.png',
    alt: 'Enter colabs name',
    dataAosCard: 'zoom-in-down',
    textColor: true,
    duration: '2000',
    link: 'https://www.facebook.com',
  },
];

export const ImageData = {
  images: [
    {
      _id: 1,
      src: '/images/p1.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'First picture',
    },
    {
      _id: 2,
      src: '/images/p2.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'Second picture',
    },
    {
      _id: 3,
      src: '/images/p3.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'Third picture',
    },
    {
      _id: 4,
      src: '/images/p4.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'Fourth picture',
    },
    {
      _id: 5,
      src: '/images/p5.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'Fifth picture',
    },
    {
      _id: 6,
      src: '/images/p6.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'Sixst picture',
    },
    {
      _id: 7,
      src: '/images/p7.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'Seventh picture',
    },
    {
      _id: 8,
      src: '/images/p1.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'Seventh picture',
    },
    {
      _id: 9,
      src: '/images/p6.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'Seventh picture',
    },
    {
      _id: 10,
      src: '/images/p3.jpg',
      alt: 'Lighthouse Design Studio',
      descriere: 'Descriere scurta',
      title: 'Seventh picture',
    },
  ],
};
